# Generated by Django 3.0.5 on 2020-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=200)),
                ('quant', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
    ]
