# Generated by Django 2.2.5 on 2020-05-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200514_1653'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table=None,
        ),
    ]
